export const quotes: string[] = [
  "Love what you do, do what you love",
  "Begin where you are",
  "Use what you have",
  "Do what you can",
  "Honour the elders, teach the young",
  "Protect and love your family",
  "Keep your craft and your skills strong",
  "Learn from your own mistakes, not only from others",
  "Look for the log in your own eye - not the splinter in your brother's",
  "Be loyal to your friends",
  "Voice your opinion, stand your ground",
  "Trust your brothers",
  "Work hard, stay humble",
  "Focus on the detail",
  "Be brave",
  "Be calm",
  "Be patient",
  "Wake up early",
  "Temper your body",
  "Live in nature",
  "Walk in the woods",
  "Climb the mountains",
  "Find time to be alone",
  "Hunt when you need food",
  "Rest when you can",
  "Work when you must",
  "Always leave your mark",
  "Take charge when others show weakness",
  "Have more, spend less",
  "More time, less convenience",
  "Craft, not business",
  "Value, not price",
  "Quality, not quantity",
  "To create, not to produce",
  "Hands, not machines"
];
